spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qwe123...
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
  #redis单机配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms #2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    jedis:
      pool:
        max-active: 1000    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1s      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5      # 连接池中的最小空闲连接
# redis集群配置
#      jedis:
#        pool:
#          max-active: 1000    # 连接池最大连接数（使用负值表示没有限制）
#          max-wait: -1s      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#          max-idle: 10      # 连接池中的最大空闲连接
#          min-idle: 5      # 连接池中的最小空闲连接
#      cluster:
#        nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
#        max-redirects: 5
#      timeout: 5000ms

#redis自定义集群配置
asset:
   cache:
     redis:
       cluster:
         nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
       pool:
         #连接池最大连接数（使用负值表示没有限制）
         max-active: 200
         #连接池最大阻塞等待时间（使用负值表示没有限制）
         max-wait: 5000
         # 连接池中的最大空闲连接
         max-idle: 50
         # 连接池中的最小空闲连接
         min-idle: 10
         #连接超时时间（毫秒）
         timeout: 5000
         #默认缓存过期时间(秒)
         defaultExpiry: 600

# 开启swagger
swagger:
  enabled: true


