spring:

  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
  #redis配置
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 6000ms
      jedis:
        pool:
          max-active: 1000    # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1s      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5      # 连接池中的最小空闲连接



# 开启swagger
swagger:
 enabled: true


